# Generated by Django 5.2 on 2026-09-16 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notifications_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
