# Generated by Django 5.2.18 on 2026-10-08 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_backfill_conversations'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='organization',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='message',
            name='organization',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization'),
        ),
    ]
