# Generated by Django 5.2.18 on 2026-10-08 03:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_alter_evaluation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='max_score',
            field=models.FloatField(default=10.0, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='weight',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
