# Generated by Django 5.2.18 on 2026-10-08 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('individual', 'Docente individual'), ('institution', 'Institución')], default='individual', max_length=20)),
                ('plan', models.CharField(choices=[('free', 'Gratis'), ('teacher', 'Docente'), ('teacher_plus', 'Docente Plus'), ('basic', 'Institución Básico'), ('standard', 'Institución Estándar'), ('enterprise', 'Institución Enterprise')], default='free', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Propietario'), ('admin', 'Administrador'), ('coordinator', 'Coordinador'), ('teacher', 'Docente'), ('student', 'Alumno'), ('parent', 'Padre o tutor')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'organization'), name='unique_membership_per_organization')],
            },
        ),
    ]
